#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WinAgent.Generators;

[Generator]
public class FeatureGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes decorated with [Feature]
        var featureClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsClassWithAttributes(s),
                transform: static (ctx, _) => GetFeatureClassInfo(ctx))
            .Where(static m => m != null);

        var compilationAndFeatures = context.CompilationProvider.Combine(featureClasses.Collect());

        context.RegisterSourceOutput(compilationAndFeatures, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsClassWithAttributes(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
    }

    private static FeatureClassInfo? GetFeatureClassInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
        if (symbol == null) return null;

        var featureAttribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "FeatureAttribute" || a.AttributeClass?.Name == "Feature");

        if (featureAttribute == null) return null;

        string path = featureAttribute.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Path").Value.Value?.ToString() ?? "";
        string description = featureAttribute.NamedArguments.FirstOrDefault(kvp => kvp.Key == "Description").Value.Value?.ToString() ?? "";

        // Find the generic base type BaseFeature<TRequest, TResponse>
        var baseType = symbol.BaseType;
        while (baseType != null && baseType.Name != "BaseFeature")
        {
            baseType = baseType.BaseType;
        }

        if (baseType == null || baseType.TypeArguments.Length != 2) return null;

        var requestType = baseType.TypeArguments[0];
        var responseType = baseType.TypeArguments[1];

        var args = new List<FeatureArgInfo>();
        if (requestType is INamedTypeSymbol namedRequestType)
        {
            // Primary constructor parameters for records
            var primaryCtor = namedRequestType.Constructors.FirstOrDefault();
            if (primaryCtor != null)
            {
                foreach (var param in primaryCtor.Parameters)
                {
                    args.Add(new FeatureArgInfo(param.Name, param.Type.ToDisplayString(), param.HasExplicitDefaultValue, param.HasExplicitDefaultValue ? param.ExplicitDefaultValue : null));
                }
            }
        }

        var mqttSubscriptions = new List<MqttSubscriptionInfo>();
        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.Name;
            if (attrName == "MqttButtonAttribute" || attrName == "MqttButton")
            {
                var id = attr.ConstructorArguments.FirstOrDefault().Value?.ToString();
                if (!string.IsNullOrEmpty(id)) mqttSubscriptions.Add(new MqttSubscriptionInfo("Button", id!));
            }
            else if (attrName == "MqttSwitchAttribute" || attrName == "MqttSwitch")
            {
                var id = attr.ConstructorArguments.FirstOrDefault().Value?.ToString();
                if (!string.IsNullOrEmpty(id)) mqttSubscriptions.Add(new MqttSubscriptionInfo("Switch", id!));
            }
            else if (attrName == "MqttSelectAttribute" || attrName == "MqttSelect")
            {
                var id = attr.ConstructorArguments.FirstOrDefault().Value?.ToString();
                if (!string.IsNullOrEmpty(id)) mqttSubscriptions.Add(new MqttSubscriptionInfo("Select", id!));
            }
        }

        return new FeatureClassInfo(symbol.ToDisplayString(), symbol.Name, path, description, requestType.ToDisplayString(), responseType.ToDisplayString(), args, mqttSubscriptions);
    }

    private static void Execute(Compilation compilation, IEnumerable<FeatureClassInfo> features, SourceProductionContext context)
    {
        if (!features.Any()) return;

        GenerateMcpTools(features, context);
        GenerateApiEndpoints(features, context);
        GenerateDocsRegistry(features, context);
    }

    private static void GenerateMcpTools(IEnumerable<FeatureClassInfo> features, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ModelContextProtocol.Server;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("");
        sb.AppendLine("namespace WinAgent.Tools");
        sb.AppendLine("{");
        sb.AppendLine("    [McpServerToolType]");
        sb.AppendLine("    public static partial class McpTools_Generated");
        sb.AppendLine("    {");

        foreach (var f in features)
        {
            string methodName = f.ClassName.EndsWith("Feature") ? f.ClassName.Substring(0, f.ClassName.Length - 7) : f.ClassName;
            // Ensure method name is unique and valid C#
            methodName = methodName.Replace("/", "_").Replace("-", "_");
            
            // To support paths like capture/screenshot in MCP, the ModelContextProtocol library uses the method name as the tool name by default.
            // Wait, ModelContextProtocol.Server usually looks at method name or `[McpServerTool("capture/screenshot")]`.
            // Let's assume `[McpServerTool("capture/screenshot")]` is valid or we just generate standard names. We will pass Name.
            sb.AppendLine($"        [McpServerTool(Name = \"{f.Path}\"), Description(\"{f.Description}\")]");
            sb.Append($"        public static async Task<string> {methodName}(IServiceProvider serviceProvider");
            
            foreach (var arg in f.Arguments)
            {
                sb.Append($", {arg.TypeName} {arg.Name.ToLowerInvariant()}");
                if (arg.HasDefaultValue)
                {
                    var val = arg.DefaultValue;
                    if (val == null) sb.Append(" = null");
                    else if (val is string s) sb.Append($" = \"{s}\"");
                    else if (val is bool b) sb.Append(b ? " = true" : " = false");
                    else sb.Append($" = {val}");
                }
            }
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine($"            var feature = serviceProvider.GetRequiredService<{f.FullName}>();");
            sb.AppendLine($"            var request = new {f.RequestTypeName}(");
            for (int i = 0; i < f.Arguments.Count; i++)
            {
                sb.Append($"                {f.Arguments[i].Name.ToLowerInvariant()}");
                if (i < f.Arguments.Count - 1) sb.AppendLine(",");
                else sb.AppendLine("");
            }
            sb.AppendLine("            );");
            sb.AppendLine("            var context = new WinAgent.Common.Features.ExecutionContext(WinAgent.Common.Features.ExecutionSource.Mcp);");
            sb.AppendLine("            var response = await feature.ExecuteAsync(request, serviceProvider, context);");
            if (f.ResponseTypeName.EndsWith("FeatureResult"))
            {
                sb.AppendLine("            if (response.FileBytes != null) return System.Text.Json.JsonSerializer.Serialize(new { Base64Image = Convert.ToBase64String(response.FileBytes), MimeType = response.FileMimeType });");
                sb.AppendLine("            if (response.PlainText != null) return response.PlainText;");
                sb.AppendLine("            return System.Text.Json.JsonSerializer.Serialize(response.JsonData);");
            }
            else
            {
                sb.AppendLine("            return System.Text.Json.JsonSerializer.Serialize(response);");
            }
            sb.AppendLine("        }");
            sb.AppendLine("");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("McpTools_Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateApiEndpoints(IEnumerable<FeatureClassInfo> features, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("");
        sb.AppendLine("namespace WinAgent");
        sb.AppendLine("{");
        sb.AppendLine("    public static class FeatureEndpoints_Generated");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void MapFeatures(this WebApplication app)");
        sb.AppendLine("        {");

        foreach (var f in features)
        {
            sb.AppendLine($"            app.MapPost(\"/api/{f.Path}\", async ({f.RequestTypeName} request, {f.FullName} feature, IServiceProvider services) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                var context = new WinAgent.Common.Features.ExecutionContext(WinAgent.Common.Features.ExecutionSource.Http);");
            sb.AppendLine("                var response = await feature.ExecuteAsync(request, services, context);");
            if (f.ResponseTypeName.EndsWith("FeatureResult"))
            {
                sb.AppendLine("                if (response.FileBytes != null) return Results.File(response.FileBytes, response.FileMimeType, response.FileName);");
                sb.AppendLine("                if (response.PlainText != null) return Results.Text(response.PlainText);");
                sb.AppendLine("                return Results.Ok(response.JsonData);");
            }
            else
            {
                sb.AppendLine("                return Results.Ok(response);");
            }
            sb.AppendLine("            }).RequireAuthorization().WithTags(\"Features\");");
            sb.AppendLine("");
        }

        sb.AppendLine("        }");
        sb.AppendLine("");
        sb.AppendLine("        public static async System.Threading.Tasks.Task<object> ExecuteFeatureAsync(string path, string jsonPayload, IServiceProvider services, WinAgent.Common.Features.ExecutionSource source = WinAgent.Common.Features.ExecutionSource.Unknown)");
        sb.AppendLine("        {");
        sb.AppendLine("            var context = new WinAgent.Common.Features.ExecutionContext(source);");
        sb.AppendLine("            switch (path.ToLowerInvariant())");
        sb.AppendLine("            {");

        foreach (var f in features)
        {
            sb.AppendLine($"                case \"{f.Path.ToLowerInvariant()}\":");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var request = System.Text.Json.JsonSerializer.Deserialize<{f.RequestTypeName}>(string.IsNullOrWhiteSpace(jsonPayload) ? \"{{}}\" : jsonPayload, new System.Text.Json.JsonSerializerOptions {{ PropertyNameCaseInsensitive = true }}) ?? new {f.RequestTypeName}();");
            sb.AppendLine($"                    var feature = services.GetRequiredService<{f.FullName}>();");
            sb.AppendLine($"                    return await feature.ExecuteAsync(request, services, context);");
            sb.AppendLine("                }");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    throw new ArgumentException($\"Unknown feature path: {path}\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("FeatureEndpoints_Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateDocsRegistry(IEnumerable<FeatureClassInfo> features, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("");
        sb.AppendLine("namespace WinAgent.Common.Features");
        sb.AppendLine("{");
        sb.AppendLine("    public static class FeatureDocsRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public static readonly List<Dictionary<string, object>> Features = new List<Dictionary<string, object>>");
        sb.AppendLine("        {");

        foreach (var f in features)
        {
            sb.AppendLine("            new Dictionary<string, object>");
            sb.AppendLine("            {");
            sb.AppendLine($"                {{ \"Path\", \"{f.Path}\" }},");
            sb.AppendLine($"                {{ \"Description\", \"{f.Description}\" }},");
            sb.AppendLine($"                {{ \"RequestType\", \"{f.RequestTypeName}\" }},");
            sb.AppendLine("                { \"Arguments\", new List<Dictionary<string, object>>");
            sb.AppendLine("                  {");
            foreach(var arg in f.Arguments)
            {
                sb.AppendLine("                      new Dictionary<string, object>");
                sb.AppendLine("                      {");
                sb.AppendLine($"                          {{ \"Name\", \"{arg.Name}\" }},");
                sb.AppendLine($"                          {{ \"Type\", \"{arg.TypeName}\" }}");
                sb.AppendLine("                      },");
            }
            sb.AppendLine("                  }");
            sb.AppendLine("                }");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("FeatureDocsRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class FeatureClassInfo
    {
        public string FullName { get; }
        public string ClassName { get; }
        public string Path { get; }
        public string Description { get; }
        public string RequestTypeName { get; }
        public string ResponseTypeName { get; }
        public List<FeatureArgInfo> Arguments { get; }
        public List<MqttSubscriptionInfo> MqttSubscriptions { get; }

        public FeatureClassInfo(string fullName, string className, string path, string description, string requestTypeName, string responseTypeName, List<FeatureArgInfo> arguments, List<MqttSubscriptionInfo> mqttSubscriptions)
        {
            FullName = fullName;
            ClassName = className;
            Path = path;
            Description = description;
            RequestTypeName = requestTypeName;
            ResponseTypeName = responseTypeName;
            Arguments = arguments;
            MqttSubscriptions = mqttSubscriptions;
        }
    }

    private class FeatureArgInfo
    {
        public string Name { get; }
        public string TypeName { get; }
        public bool HasDefaultValue { get; }
        public object? DefaultValue { get; }

        public FeatureArgInfo(string name, string typeName, bool hasDefaultValue, object? defaultValue)
        {
            Name = name;
            TypeName = typeName;
            HasDefaultValue = hasDefaultValue;
            DefaultValue = defaultValue;
        }
    }

    public class MqttSubscriptionInfo
    {
        public string Type { get; } 
        public string Id { get; }
        public MqttSubscriptionInfo(string type, string id) { Type = type; Id = id; }
    }
}
