DOMAIN = "win_agent"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_TOKEN = "token"
CONF_NAME = "name"

SERVICE_NOTIFY = "notify"
SERVICE_START_PROCESS = "start_process"
SERVICE_LOCK = "lock"
SERVICE_SHUTDOWN = "shutdown"
SERVICE_REBOOT = "reboot"
SERVICE_LOGOUT = "logout"
SERVICE_LOGIN = "login"
SERVICE_TYPE_LOGON = "type_logon"
SERVICE_CLEAR_CREDENTIALS = "clear_credentials"
SERVICE_AUDIO = "audio"
SERVICE_DISPLAYS = "displays"
SERVICE_DEVICES = "devices"
SERVICE_UPDATE = "update"
SERVICE_SCREENSHOT = "screenshot"
SERVICE_EXECUTE_FEATURE = "execute_feature"

